"""empty message

Revision ID: 1b99807ae7cf
Revises: 7248cbf69296
Create Date: 2026-02-19 16:25:45.547716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1b99807ae7cf'
down_revision: Union[str, Sequence[str], None] = '7248cbf69296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.alter_column('player1_id',
               nullable=True)
        batch_op.drop_column('first_player_id')

    with op.batch_alter_table('playerresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('swiss_event_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('swiss_tie_breaker_points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cut_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cut_draws', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cut_event_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cut_tie_breaker_points', sa.Integer(), nullable=True))
        batch_op.alter_column('swiss_rank',
               nullable=False)
        batch_op.alter_column('cut_wins',
               nullable=True)
        batch_op.alter_column('cut_losses',
               nullable=True)
        batch_op.drop_column('rank')
        batch_op.drop_column('points_at_event')

    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_count', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_column('team_count')

    with op.batch_alter_table('playerresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_at_event', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('rank', sa.INTEGER(), nullable=False))
        batch_op.alter_column('cut_losses',
               nullable=False)
        batch_op.alter_column('cut_wins',
               nullable=False)
        batch_op.alter_column('swiss_rank',
               nullable=True)
        batch_op.drop_column('cut_tie_breaker_points')
        batch_op.drop_column('cut_event_points')
        batch_op.drop_column('cut_draws')
        batch_op.drop_column('cut_rank')
        batch_op.drop_column('swiss_tie_breaker_points')
        batch_op.drop_column('swiss_event_points')
        batch_op.drop_column('team_name')

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_player_id', sa.INTEGER(), nullable=True))
        batch_op.alter_column('player1_id',
               nullable=False)

    # ### end Alembic commands ###
