"""empty message

Revision ID: 43fd11caae19
Revises: 
Create Date: 2026-01-23 18:06:07.239075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '43fd11caae19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playerresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('swiss_rank', sa.Integer(), nullable=True),
    sa.Column('swiss_wins', sa.Integer(), nullable=False),
    sa.Column('swiss_losses', sa.Integer(), nullable=False),
    sa.Column('swiss_draws', sa.Integer(), nullable=False),
    sa.Column('cut_wins', sa.Integer(), nullable=False),
    sa.Column('cut_losses', sa.Integer(), nullable=False),
    sa.Column('list_json', sa.JSON(), nullable=True),
    sa.Column('points_at_event', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('round_type', sa.String(), nullable=True),
    sa.Column('scenario', sa.String(), nullable=True),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('player1_score', sa.Integer(), nullable=False),
    sa.Column('player2_score', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('first_player_id', sa.Integer(), nullable=True),
    sa.Column('is_bye', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['player1_id'], ['playerresult.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['playerresult.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_table('playerresult')
    op.drop_table('tournament')
    # ### end Alembic commands ###
