"""empty message

Revision ID: 7248cbf69296
Revises: 43fd11caae19
Create Date: 2026-01-24 10:37:22.949278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import m3tacron.backend.data_structures.location

# revision identifiers, used by Alembic.
revision: str = '7248cbf69296'
down_revision: Union[str, Sequence[str], None] = '43fd11caae19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', m3tacron.backend.data_structures.location.LocationType(), nullable=True))
        batch_op.drop_column('city')
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###
